name: ej4-workflow

on: 
  push:
    branches:
      - main

jobs:
   tareas: 
    runs-on: ubuntu-latest
     steps: 
      - name: Descargar el codigo
        uses: actions/checkout@v4

      - name: Instalar Logstash
        run: |       
             wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elastic-keyring.gpg
             sudo apt-get install apt-transport-https
             sudo apt-get update && sudo apt-get install logstash

      - name: Validar logstash.conf
        run: sudo /usr/share/logstash/bin/logstash -t -f logstash.conf
        
      
